query getCredential($id: uuid!) {
  credentials_by_pk(id: $id) {
    updated_at
    target_id
    skills
    pow
    name
    knowledges
    issuer_id
    image
    id
    info
    description
    dao_id
    created_at
    ceramic
    attitudes
    namespace
    status
    dao {
      background_url
      categories
      created_at
      description
      ens
      id
      logo_url
      name
      slug
    }
  }
}
